Merge UI Work with Master
MichaelKowal/Skema pull request #5
Opened 2018-09-25 20:27 UTC by tokkin

This has all of the navigation bar and updated CSS, as well as Bootstrap integration in the skema.html

2018-09-26 22:06 UTC, ErikSearle requested changes
Looks like a very good start to the UI design. If you haven't already, you should start taking a look at jinja and use it to make your life easier when building HTML pages.

2018-09-26 22:06 UTC, ErikSearle commented on app/templates/info.html
> +
If we download and include these js and css files in our project, we can use flask-assets to combine them all into a single minifyed css file and a single minifyed js file, which we can import in a single line in our html to make this look much cleaner. This will also reduce our dependencies on these external urls which protects us from a scenario where these sites are down or the version is updated and it makes our site blow up.

2018-09-26 22:06 UTC, ErikSearle commented on app/templates/info.html
> +<html lang="en" dir="ltr">
We shouldn't need a dir tag anymore. It has been deprecated as css now covers this. https://www.computerhope.com/jargon/h/html-dir-tag.htm

2018-09-26 22:06 UTC, ErikSearle commented on app/templates/info.html
> +<!DOCTYPE html>
What is the end game purpose of this info.html file?

2018-09-26 22:06 UTC, ErikSearle commented on app/templates/skema.html
> +          <div class="form-check">
This is a good prototype, but once we start serving this html from the flask app, we'll be able to cut down on a lot of this code by using jinja tags. For example, the repetition of the next 4 sections can be dealt with in a jinja for-loop.

2018-09-26 22:06 UTC, ErikSearle commented on app/templates/skema.html
> +  <script type="text/javascript">
Ideally this should be in a js file, and not written directly into the html. This isn't a big issue obviously as it's only 4 lines, but it's a dangerous game to start including a lot of js in html files.

2018-09-26 22:06 UTC, ErikSearle commented on app/views.py
> +'''
Why is this commented out?

2018-09-26 22:06 UTC, ErikSearle commented on .gitignore
> +venv/*
It looks like you named you virtualenv "env" not "venv". Can you fix this file, and then delete all of the env/* files from this PR please?

2018-09-29 17:33 UTC, tokkin commented on app/templates/info.html
> +<!DOCTYPE html>
This was something else I was working on. That can go away.

2018-09-29 17:36 UTC, tokkin commented on app/templates/skema.html
> +          <div class="form-check">
Sweet. I'm looking into jinja templates.

2018-10-08 04:33 UTC, ErikSearle approved these changes
Looks good to me. Thanks for fixing the venv stuff and downloading all the files.

2018-10-08 04:36 UTC, ErikSearle commented
Before you merge, could you also get rid of the ds store files that mac creates?

2018-10-09 18:17 UTC, merged